version: '3'
services:
        mysql:
                build:
                        context: ${BASE_DIR}/mysql
                        dockerfile: Dockerfile
                        args:
                                VERSION: ${VERSION}
                image: mysql-8.0
                container_name: mysql
                hostname: mysql-${SYSTEM_LOCAL_HOST_IP}
                restart: unless-stopped
                env_file:
                        - ${BASE_DIR}/.env
                environment:
                        - MYSQL_ROOT_PASSWORD=TestSQLPassword789
                networks:
                        management:
                                ipv4_address: ${SYSTEM_MYSQL_NODE_IP}
                ports:
                        - 3306:3306/tcp
                logging:
                        driver: "json-file"
                        options:
                                max-size: "10m"
                                max-file: "5"

networks:
        management:
                driver: bridge
                ipam:
                        driver: default
                        config:
                                - subnet: 172.168.1.0/24
